rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.lang.live/room/5664344
  is_listening: false
- url: https://live.bilibili.com/22603245
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
  fix_flv_at_first: true
timeout_in_us: 60000000
notify:
  telegram:
    enable: false
    withNotification: true
    botToken: ""
    chatID: ""
  email:
    enable: false
    smtpHost: smtp.qq.com
    smtpPort: 465
    senderEmail: ""
    senderPassword: ""
    recipientEmail: ""
  gotify:
    enable: false
    serverURL: ""
    token: ""
    priority: 5
app_data_path: .appdata
read_only_tool_folder: ""
tool_root_folder: ""
